[package]
name = "actix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "core"
path = "core/lib.rs"

[[bin]]
name = "actix"
path = "src/main.rs"

[dependencies]
actix-web="3.3.2"
actix-files = "0.5.0"

serde="1.0.126"
serde_json = "1.0.64"
