[package]
name = "actix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "core"
path = "core/lib.rs"

[[bin]]
name = "actix"
path = "src/main.rs"

[dependencies]
actix = "*"
actix-web= {version =  "3.3.2", features = ["rustls"] }
actix-files = "0.5.0"
openssl = "0.10.36"
rustls = "0.18.1"

serde="1.0.126"

diesel = { version="1.4.7", features = ["postgres", "r2d2"]}
r2d2 = "0.8.9"
dotenv = "0.15.0"
lazy_static = "1.4.0"
